name: travel_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2
  shape_of_view_null_safe: ^2.0.0
  google_fonts: ^6.3.2
  water_drop_nav_bar: ^2.2.0+5
  flutter_svg: ^2.2.1
  pin_code_fields: ^8.0.1
  timer_count_down: ^2.2.2
  supabase_flutter: ^2.10.2
  provider: ^6.1.5+1
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.0.1
  gap: ^3.0.1
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^10.9.1
  bottom_bar_matu: ^1.5.0
  animated_notch_bottom_bar: ^1.0.3
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_map_tile_caching: ^10.1.1
  flutter_map_animations: ^0.9.0
  flutter_map_marker_popup: ^8.1.0
  calendar_timeline: ^1.1.3
  easy_date_timeline: ^1.1.3
  table_calendar: ^3.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.0.7
  flutter_zalopay_sdk: ^0.1.14
  path_provider: ^2.1.0
  syncfusion_flutter_pdfviewer: ^31.1.19
  syncfusion_flutter_pdf: ^31.1.19
  hand_signature: ^3.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/docx/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
